### ISSUE TITLE
issues

### ISSUE THREAD

**Issue by thelegitdolt** [Uraneptus/Sullys-Mod#10]
Jade ore doesn’t generate. Could possibly I’m getting super duper unlucky, but I cannot seem to find any jade at all. I was definitely in a jungle too I think

also, there’s no recipe for smwlting raw jade to actual jade

**Comment by ManaStar** [comment]
So as for the ore bit I do believe you are rather unlucky, is in the same range as copper to my understanding and I have seen it generate in the current build so it might come down to a mod compat issue. If I could get your modlist so I could check for myself that would be great.

 As for the raw jade part you are supposed to shift + right click a grindstone with it in your hand to polish it, though we are looking into ways of making this more obvious to the player.

**Comment by thelegitdolt** [comment]
i think it should just be smelting it like any other raw ore honestly, logic doesn't really matter much in a block game. gunna do some further testing with this too

**Comment by thelegitdolt** [comment]
nvm i was able to see the jade ore idk what happened there
