### ISSUE TITLE
Game crashes upon generating new worlds with newest version of Sully's Mod installed (3.2.0)

### ISSUE THREAD

**Issue by endro555** [Uraneptus/Sullys-Mod#104]
Hey hi, I'm having an issue where my game crashes when I click "create new world", and I couldn't figure out why until I removed mods one by one and figured out that Sully's Mod was crashing it. From what I can see in the logs and by searching 'sully', it says that polished jade doesn't exist? I don't know if it's actually the problem but it does look concerning and might be related to it
![image](https://github.com/user-attachments/assets/1f00b92d-282d-4fbd-a9ee-00e33b1b5cb8)
Here are the logs for the crash:
[2024-12-13-16.log](https://github.com/user-attachments/files/18132523/2024-12-13-16.log)

**Comment by Uraneptus** [comment]
Have you modified the game with datapacks?

**Comment by Uraneptus** [comment]
Or is the modpack you're using modifying the data files?

**Comment by endro555** [comment]
> Have you modified the game with datapacks?

I do have a datapack that modifies generation, I'll try disabling that and see what happens

**Comment by endro555** [comment]
It was the Continents datapack 💔 
Not sure why it doesn't work with it but I'll keep that in mind

**Comment by Uraneptus** [comment]
We changed the registry names of some items, they need to update this datapack in order for it to work with 3.2.0, could you send me tge link to this datapack maybe I can contact the author

**Comment by Uraneptus** [comment]
update: it was probably spelunkery

**Comment by Git-Reternos** [comment]
same issues when install with spelunkery

**Comment by Uraneptus** [comment]
The spelunkery dev will fix this soon, probably!
