### ISSUE TITLE
Missing namestrings for Petrified Sign and Petrified Hanging Sign

### ISSUE THREAD

**Issue by SpiderM1843** [Uraneptus/Sullys-Mod#106]
![2024-12-13_22 55 26](https://github.com/user-attachments/assets/9c9b20c2-87e2-41a1-93ff-d0ed1c8ddee4)

**Comment by thelegitdolt** [comment]
the molten amber fluid also has no translations

**Comment by Uraneptus** [comment]
yup that's why I mentioned this issue-number in your issue, so they are both mentioned in here
