### ISSUE TITLE
Item Not Found Error: 'sullysmod:polished_jade' Causes Crash in Minecraft Forge 1.20.1

### ISSUE THREAD

**Issue by chrispzg** [Uraneptus/Sullys-Mod#109]
[crash-2024-12-14_18.11.47-client.txt](https://github.com/user-attachments/files/18137787/crash-2024-12-14_18.11.47-client.txt)

**Comment by Uraneptus** [comment]
That's not directly caused by us.
If you have a mod like spelunkery installed that has sullysmod compat, those mods or datapacks will break until the mod author fixes it! The spelunkery dev already knows about this
