### ISSUE TITLE
Petrified Sign, Petrified Hanging Sign, and amber fluid are missing translations

### ISSUE THREAD

**Issue by thelegitdolt** [Uraneptus/Sullys-Mod#111]
<img width="607" alt="Screenshot 2024-12-14 at 2 25 32 PM" src="https://github.com/user-attachments/assets/cdb94cbd-4eb9-4192-a76b-414dbfe35679" />
<img width="759" alt="Screenshot 2024-12-14 at 2 25 30 PM" src="https://github.com/user-attachments/assets/4fb8c09f-2a2f-4aa2-8e06-682677d0d5ff" />
<img width="765" alt="Screenshot 2024-12-14 at 2 25 27 PM" src="https://github.com/user-attachments/assets/68dd8e26-c8c5-4ea7-8c0a-98b8d0c578dc" />

**Comment by Uraneptus** [comment]
duplicate to #106
