### ISSUE TITLE
entities seem to think they're in amber when picked up with carry on

### ISSUE THREAD

**Issue by BurningSulphur** [Uraneptus/Sullys-Mod#115]
when you pick up a cow that's just been in amber it displays it as if it's in amber
![2024-12-15_00 32 06](https://github.com/user-attachments/assets/1c5f278d-eddc-4d08-a1cb-785e77e0537a)

Expected behaviour: not show as if it's in amber when it wasn't in amber.

Note: you can't pick up the cow while it is in the amber, you can pick up the amber block though

**Comment by Uraneptus** [comment]
They are supposed to keep this data, but they are not supposed activate the amber layer when picked up with carry on.
