### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by asdasdasadg** [Uraneptus/Sullys-Mod#12]

**Comment by ManaStar** [comment]
Please post a log so that we can figure this out!

**Comment by asdasdasadg** [comment]
> Please post your latest.log file so that we can figure this out!

https://github.com/Uraneptus/Sullys-Mod/files/8889604/latest.log

**Comment by asdasdasadg** [comment]
> This mod requires [Blueprint](https://www.curseforge.com/minecraft/mc-mods/blueprint/files), which you don't seem to have and needs to be installed in order for the mod to work.

i do?
https://user-images.githubusercontent.com/84078980/173321957-6cbdfc29-0bc0-412a-abc2-036257c66f3e.png

**Comment by asdasdasadg** [comment]
> This mod requires [Blueprint](https://www.curseforge.com/minecraft/mc-mods/blueprint/files), which you don't seem to have and needs to be installed in order for the mod to work.

oh nvm i think i see the issue here lmao
