### ISSUE TITLE
Game console says "1" when polishing Jade on a grindstone.

### ISSUE THREAD

**Issue by ExDrill** [Uraneptus/Sullys-Mod#19]
https://github.com/Uraneptus/Sullys-Mod/blob/1.19.x/src/main/java/com/uraneptus/sullysmod/core/events/SMPlayerEvents.java#L79
This seems to be causing this.

**Comment by Uraneptus** [comment]
Oh that's my bad, I thought I removed this. Thanks for reporting ^^
