### ISSUE TITLE
Copper  golem dont have animations.

### ISSUE THREAD

**Issue by FrogPlayzz** [Uraneptus/Sullys-Mod#2]
I find in mod animation files: copper golem json, but in game he not have animations.
![2022-03-19](https://user-images.githubusercontent.com/99333919/159111001-81d790de-a37c-4f1f-a84b-c9e09c0ca91c.png)

**Comment by Uraneptus** [comment]
The newest version should have walking animation, but as I already said in the last issue you opened here "Do not report things in an indev mod!"
