### ISSUE TITLE
[1.19.2] Jade Shield has 2 attack speed icons from Quark for some reason

### ISSUE THREAD

**Issue by BugmanBugman** [Uraneptus/Sullys-Mod#37]
![2022-12-20_14 47 48](https://user-images.githubusercontent.com/40730042/208763445-97b516ac-c5e9-437a-a8f9-a8224cd49dae.png)

**Comment by Uraneptus** [comment]
That's know, it's not really a bug, tho I will look into how I could remove this. Thank you for reporting this! I will let you know once this is fixed!
