### ISSUE TITLE
New idea

### ISSUE THREAD

**Issue by MinecraftModderDailyDoseOfMods** [Uraneptus/Sullys-Mod#55]
1. Jade turret
They can be build by players and bound owner to them or spawn in upcoming jade dungeons
If they spawn naturaly they always have 3 arrows to attack players
If build by player it needs to have a projectile hit them or they pickup projectile items like snowballs or arrows and shoot them right back at the attacker. They often lure range mobs to shoot them. Both wild and build always drop a flinger totem on death
 Build by:
Flinger totem
Jade Dispenser
Polished Jade Block x2

2. Jade arrow
Build specifically for jade turret
They fling back and fourth on normal block and stick on jade block. Can be tipped

3. Jade golem
New boss in jade dungeons
They immune to projectiles and have similar behavior as jade turet.
They drop a flinger totem and a jade dispenser on death

4. Jade dispenser
Have similar behaviour as jade turret.

5.Pot golem tweaks
  1.They can be tamed
  2.If tamed they give you a chest storage space
  3.Pickup items. Both wild and tamed

**Comment by Uraneptus** [comment]
I have sent those ideas to Sully to consider what they like and dislike. Thank you for your suggestions ^^

**Comment by MinecraftModderDailyDoseOfMods** [comment]
Also-1-more-idea:Jade glass
