### ISSUE TITLE
Jade Ore is unable to be smelted

### ISSUE THREAD

**Issue by thelegitdolt** [Uraneptus/Sullys-Mod#57]
In vanilla, all the ores have a smelting recipe to be made into their respective ingot/gem. But Jade Ore does not.

**Comment by Uraneptus** [comment]
Since you're not supposed to smelt rough jade, there is no smelting recipe for the ore block! However I don't think we have added a polishing recipe for the ore. I will think about if a polishing recipe here makes sense and if so I'll add it!
