### ISSUE TITLE
Suggestion: Add polishing compatibility with other mods

### ISSUE THREAD

**Issue by Numerosityy** [Uraneptus/Sullys-Mod#62]
You can right click with modded blocks and their polished version will be made
Mods that could have this functionality would include:
Quark
Unearthed
Unusual End
Abundant Atmosphere
Twigs
Regions Unexplored
Darker Depths
Architect's Palette
Enlightend
Stoneworks
Sculpt
NotEnoughBlocks

Alternative solution:
Possibly use a script to automatically recognize these types of blocks

**Comment by Uraneptus** [comment]
Hey, we really want to support as many mods as possible, but adding recipes to all these mods will take an incredible amount of time and effort from our team. We want to  spend this time on other features tho.
However, you or anyone else can open a PR here on github and add the json recipe files for any other mod.
Just add the files to: `src/main/resources/data/sullysmod/recipes/grindstone_polishing`

**Comment by Numerosityy** [comment]
I'd definitely be down to do it, thanks for the quick reply

**Comment by Uraneptus** [comment]
If you add the recipe files, make sure it looks like this:
```
{
  "type": "forge:conditional",
  "recipes": [
    {
      "conditions": [
        {
          "type": "forge:mod_loaded",
          "modid": "quark"
        }
      ],
      "recipe": {
        "type": "sullysmod:grindstone_polishing",
        "experience": 0,
        "ingredient": "quark:calcite",
        "result": "quark:polished_calcite",
        "resultCount": 1
      }
    }
  ]
}
```
Otherwise the game will crash when trying to load a world.
If you have any question feel free to DM me or reach out to us in our discord!

**Comment by Numerosityy** [comment]
Is there a system like the Polymorph mod that checks for duplicate recipes with the grindstone right click recipes? Some of these blocks are identical and have the same recipe, but I don't want to cause a crash if both mods are installed

**Comment by Numerosityy** [comment]
Also here's the recipes:
https://drive.google.com/file/d/1opjIJTvmp78S-iebTQQOtHyc1SzFQpqw/view?usp=sharing

**Comment by Numerosityy** [comment]
@Uraneptus Sorry I don't know how I should PR this, if you want to do it go right ahead

**Comment by Uraneptus** [comment]
Don't worry I can add the files! Thank you for the effort. ^^

**Comment by Uraneptus** [comment]
> Is there a system like the Polymorph mod that checks for duplicate recipes with the grindstone right click recipes? Some of these blocks are identical and have the same recipe, but I don't want to cause a crash if both mods are installed

Could you tell me which blocks from which mods you are talking about?

**Comment by Numerosityy** [comment]
> > Is there a system like the Polymorph mod that checks for duplicate recipes with the grindstone right click recipes? Some of these blocks are identical and have the same recipe, but I don't want to cause a crash if both mods are installed
> 
> Could you tell me which blocks from which mods you are talking about?

Well I was a little worried about the fact that there are duplicate blocks that use the same recipes (ex: quark and twigs both have polished calcite). But honestly things like this aren't that inconvenient so I just left out one of the recipes. I wouldn't be too worried about this

**Comment by Numerosityy** [comment]
Do you think you are gonna release the mod with just this change for 1.19.2 now? Or are you gonna make more changes and then release?

**Comment by Uraneptus** [comment]
We have a few small changes we're currently working on and we'll release a last 1.19 update with your recipes and those changes.

**Comment by Uraneptus** [comment]
> Well I was a little worried about the fact that there are duplicate blocks that use the same recipes (ex: quark and twigs both have polished calcite). But honestly things like this aren't that inconvenient so I just left out one of the recipes. I wouldn't be too worried about this

Ah I see what you mean. A system that would let you decide between a few available results for the same input item would be quite useful.
I will put this on my possible-ideas list.
If you have something in mind as to how a system like this could look like in game, let me know

**Comment by Numerosityy** [comment]
> We have a few small changes we're currently working on and we'll release a last 1.19 update with your recipes and those changes.

Sounds good, thanks
