### ISSUE TITLE
3.0.0 server connection issue

### ISSUE THREAD

**Issue by Typhonidite** [Uraneptus/Sullys-Mod#70]
Upon attempting to join server,

> Internal Exception: io.netty.handler.codec.DecoderException:
> io.netty.handler.codec.EncoderException: java.io.UTFDataFormatException:
> malformed input around byte 2
![Screenshot (89) cropped](https://github.com/Uraneptus/Sullys-Mod/assets/71224403/b91221da-9970-4ed1-8b70-6eed15f91294)

Log:
[latest (1).log](https://github.com/Uraneptus/Sullys-Mod/files/12772930/latest.1.log)

**Comment by Uraneptus** [comment]
Thanks, that already fixed and I will release a fix soon!
