### ISSUE TITLE
[filing an issue for a whole other mod but i refuse to use twitter] sully's peeves leg armor slot is the wrong shade

### ISSUE THREAD

**Issue by sisby-folk** [Uraneptus/Sullys-Mod#72]
We're filing an issue for sully's peeves considering this is an actual tracker and the respack is ARR. Soz. Bother sully for me thanks.

Vanila:

![vanilla](https://raw.githubusercontent.com/InventivetalentDev/minecraft-assets/1.20.1/assets/minecraft/textures/item/empty_armor_slot_leggings.png)

![image](https://github.com/Uraneptus/Sullys-Mod/assets/55819817/9c33d097-a947-4841-9387-225bfec1251e)

Sully's Peeves:

![sully's peeves](https://github.com/Uraneptus/Sullys-Mod/assets/55819817/3d9c827c-8e1d-4de0-b34a-b98e2c427418)

![image](https://github.com/Uraneptus/Sullys-Mod/assets/55819817/7bb69bc3-138f-4a69-bcca-996d5f89a367)

shown in fabric 1.20.1

**Comment by Uraneptus** [comment]
Please don't open issues for not sullysmod related things here. Leave a comment on curseforge or join Sully's discord.

**Comment by sisby-folk** [comment]
We get sully's peeves from https://modrinth.com/resourcepack/sullys-peeves - there's no link to any discord there - or any way to leave comments at all.

Does the discord have any issue trackers or channels for Sully's peeves? or is it unrelated?

**Comment by Uraneptus** [comment]
Seems like sully forgot to link the discord. I have already mentioned the texture issue to him, but if there's anything else in the future, here is the discord: [Link](https://discord.gg/nuVuQ4v)
And yes the discord has a channel dedicated to Sully's peeves!
