### ISSUE TITLE
1.20.1 server crash on startup

### ISSUE THREAD

**Issue by oof100200** [Uraneptus/Sullys-Mod#80]
https://pastebin.com/YqaZjR0C
↑Crash Log

**Comment by Uraneptus** [comment]
Hi, could you test if the file I uploaded in issue #79, fixes this problem?

**Comment by oof100200** [comment]
> Hi, could you test if the file I uploaded in issue #79, fixes this problem?

The server is still crashing, it's doesn't works.

**Comment by Uraneptus** [comment]
Okay then I'll try something else

**Comment by Uraneptus** [comment]
[sullysmod-3.1.0-beta.zip](https://github.com/Uraneptus/Sullys-Mod/files/13746373/sullysmod-3.1.0-beta.zip)
Please try this file

**Comment by oof100200** [comment]
> [sullysmod-3.1.0-beta.zip](https://github.com/Uraneptus/Sullys-Mod/files/13746373/sullysmod-3.1.0-beta.zip) Please try this file

it works, thank you.
