### ISSUE TITLE
NullPointerException when calling TortoiseShell.getOwnerUUID()

### ISSUE THREAD

**Issue by Snownee** [Uraneptus/Sullys-Mod#81]
[Here](https://github.com/Uraneptus/Sullys-Mod/blob/1.20.x/src/main/java/com/uraneptus/sullysmod/common/entities/TortoiseShell.java#L70) a null check is missing, which leads to a NullPointerException.

Also, I don't think it's appropriate to store an entity in the class, which would prevent the game from releasing memory. The default implementation is fast enough.

**Comment by Uraneptus** [comment]
Oh thank you! I'll fix this.
What do you mean with default implementation here tho?
Do you mean only using the UUID and not the entity directly?

**Comment by Snownee** [comment]
> Oh thank you! I'll fix this. What do you mean with default implementation here tho? Do you mean only using the UUID and not the entity directly?

The default implementation is defined in `OwnableEntity`

**Comment by Uraneptus** [comment]
I figured you meant that! Changed that together with the bugfix
Thank you!
