### ISSUE TITLE
Bouldering Zombies spawn in Deep Dark biomes

### ISSUE THREAD

**Issue by PaperfishStudios** [Uraneptus/Sullys-Mod#82]
![2023-12-30_16 03 51](https://github.com/Uraneptus/Sullys-Mod/assets/53896042/3515fa8e-87f5-4a20-a68f-b176f5f0038f)
^ this screenshot is taken in a single-biome deep dark world using sully's mod 3.1.1, but the same issue happens in a regular world (and they spawn a LOT)

no mods were installed except sully's, blueprint 7.0.0 & geckolib 4.3.1 (and forge 47.2.0)

**Comment by Uraneptus** [comment]
Ah yeah that was an oversight on my end. Will be fixed in the next update!
Thank you ^^
