### ISSUE TITLE
Related to #82, bouldering zombies also spawn in mushroom fields

### ISSUE THREAD

**Issue by Mechalopa** [Uraneptus/Sullys-Mod#83]
bcd3f2d66df10897dfb52b94d2359feaf0ffc0de
The tag `#forge:is_mushroom` also contains `minecraft:mushroom_fields`.

**Comment by Uraneptus** [comment]
Hi, thank you!
While this is true, the zombie should not spawn on the mushroom field island. It cannot spawn above y level 0, meaning it can only spawn underground. However caves can be marked as mushroom_field as far as I know, that's why it's included in the tag.
