### ISSUE TITLE
Crash on startup (sullysmod-3.1.2-beta)

### ISSUE THREAD

**Issue by abby-cadabra** [Uraneptus/Sullys-Mod#89]
Hi there,

Adding Sullys Mod to a pre-existing world (with no other new mods or datapacks) caused "Errors in currently selected datapacks prevented the world from loading." Attempting to load in safe mode says the world is corrupted.

When trying to create a new world with Sullys installed, the screen hangs indefinitely on "preparing for world generation." 

Removing Sullys (and Blueprint) allows the 'corrupted' world to load normally, and also allows for new world generation. 

I have attached the latest crash log below.

[2024-03-03-7[1].log](https://github.com/Uraneptus/Sullys-Mod/files/14471837/2024-03-03-7.1.log)

Details:
Minecraft 1.20.1
Forge-47.2.20
Sullys 3.1.2-beta
Blueprint 1.20.1-7.0.1.jar

Happy to provide any other details as needed.

**Comment by Uraneptus** [comment]
Use the previous blueprint version! 7.0.1 is not compatible with Sullys-Mod because they removed many quark compat files!
