### ISSUE TITLE
Crash with neoforge on projectile impact with jade

### ISSUE THREAD

**Issue by noukherne** [Uraneptus/Sullys-Mod#91]
Firing an arrow to a jade block causes the server to crash on impact. Seems to be related with ProjectileImpactEvent
I haven't tested if there is a specific version of neoforge where it works

[debug-2.log](https://github.com/Uraneptus/Sullys-Mod/files/14817326/debug-2.log)

**Comment by Uraneptus** [comment]
The changelog of version 3.1.2, clearly states, that the version is not compatible with neoforge!

**Comment by noukherne** [comment]
My bad, sorry for the issue

**Comment by Uraneptus** [comment]
No problem at all ^^
A possible fix is planned for the next update btw!
