### ISSUE TITLE
Crash on monster spawner bouldering zombie replacement

### ISSUE THREAD

**Issue by Liamgrayskull** [Uraneptus/Sullys-Mod#92]
[crash-2024-04-20_22.47.52-server.txt](https://github.com/Uraneptus/Sullys-Mod/files/15050763/crash-2024-04-20_22.47.52-server.txt)

**Comment by Uraneptus** [comment]
More info needed! When exactly does the game crash? Which other mods have you installed? Which mod loader version are you using? Does the crash also happen without the connector mod in the same situation?

**Comment by Uraneptus** [comment]
Also, is your client crashing or some server you are on? And could you please provide the latest.log as well?

**Comment by Tosh022402** [comment]
Im having the same issue, this happens randomly when loading chunks something about "net.minecraft.world.level.levelgen.feature.MonsterRoomFeature.handler$fij000$sullysmod"

**Comment by Tosh022402** [comment]
Here is the log 
[2024-05-14-3.log](https://github.com/Uraneptus/Sullys-Mod/files/15298785/2024-05-14-3.log)
Using forge 47.2.0 sullysmod-3.1.2-beta.jar,
and the latest version of sinytra connector

**Comment by TheFoxsGuide** [comment]
Same problem I think, every time I try to play in a single player world, there were times that the game freeze and then crashes, showing the "Feature placement" message.

[crash-2024-09-11_17.30.57-server.txt](https://github.com/user-attachments/files/16971405/crash-2024-09-11_17.30.57-server.txt)

I have the Sinytra connector installed but I played with both connector and Sully's Mod at the same time years ago and there was no problem. I'm currently playing with Forge 47.3 and the problem happens when rendering new chunks (there's no other way to describe it). 

Here's the modlist:
[MODLIST.txt](https://github.com/user-attachments/files/16971482/MODLIST.txt)

**Comment by Uraneptus** [comment]
Can you confirm this is happening with the same versions and without connector too?

**Comment by TheFoxsGuide** [comment]
Hi again, I tried changing the Forge version from 47.3 to 47.2 and still crashes. However, when removing connector and the fabric mods, the mod seems to work perfectly.

The way I test the crash was going down to the deepslate level and placing a Boulder Zombie Generator. Without the connector works fine, but with the connector it seems to struggle and immediatly crashes when trying to join the world again.

Also, I tested Sully's mod using an older version (1.3.1) and at the beginning seemed to work perfectly, so I saved and quit and... crashed. I tested again with that version and it does the same crash when entering.

**Comment by Uraneptus** [comment]
Does it happen with our mod and only the connector? Or could you point point to some other mod that might be causing a conflict?

**Comment by piber20** [comment]
I'm not used to posting in GitHub issues, but I thought I'd chime in here. I can confirm that this can happen without connector. Apologies if my mod list looks like a mess, I am attempting to set up a personal mod pack and your mod has been one I found to be charming during the last times I attempted to mod Minecraft.

Log:
https://mclo.gs/EwbK6F6

**Comment by Uraneptus** [comment]
thanks @piber20 for confirming. Do you think we could chat on discord or somewhere to better debug this?

**Comment by piber20** [comment]
I was able to narrow the mod list down to these mods:
- Blueprint
- Geckolib
- More Mob Variants
- Sully's Mod
- Unsafe World Random Access Detector

It must be some kind of conflict that occurs specifically between the last three, disabling one of them stops the crash, no matter which it is.

Minecraft version: 1.20.1
Java version: 17.0.12
Forge version: 47.3.10
Log: https://mclo.gs/G6HpDxX
Tested using world seed, crashes right at spawn: 721919120341564689

I will repost this to the two other mods, if they have a way to report bugs too. Hopefully this helps!

**Comment by piber20** [comment]
I have reposted to More Mob Variants' issue tracker: https://github.com/nyuppo/MobVariantsForge/issues/3

Crash also seems to happen regardless of what the deepslate zombie spawn config setting is set to.

**Comment by Uraneptus** [comment]
Thanks a lot, all of that is very helpful 🙏
I'll try replicating this with the mods you mentioned in the dev environment and see what I can do!

**Comment by Uraneptus** [comment]
Crash is fixed
