### ISSUE TITLE
Bouncing Projectile Crashes on NeoForge

### ISSUE THREAD

**Issue by GameGuruGreenGryphon** [Uraneptus/Sullys-Mod#97]
### Versions
Minecraft: 1.20.1
NeoForge: 47.1.106
Sully's Mod: 3.1.2-beta
GeckoLib 4: 4.4.7
Blueprint: 7.1.0
### Issue
Bouncing projectiles off of Block of Polished Jade crashes the game. Loading the world again crashes the game.
When I threw an Ender Pearl at a Block of Polished Jade, the game crashed as soon as the pearl would bounce.
Also crashes with Snowballs and Tridents.
### Crash Log
https://gist.github.com/GameGuruGreenGryphon/eadbe91535cbb1e52323e4c7ff01aa25

**Comment by Uraneptus** [comment]
Version 3.1.2 is not compatible with Neoforge. Which is clearly stated in the changelog of that version. I would advise switching to forge here. Neoforge will be supported and required in mc version 1.21

**Comment by zenithBemusement** [comment]
Just as a heads up, when using the Prism launcher, attempting to download the mod on a neoforge instance will default to 3.1.2 and not give any warning on the matter. I don't know if there's anything you can do about this, but I figured I aughta give you the heads up (cause I only learned that 3.1.2 is incompatible while checking your issues page for incompatibilities)

**Comment by Uraneptus** [comment]
We can't really do anything about that sadly. Mentioning this incompatibility in the changelog is the only thing we can do. But since the next version we will be releasing is still not compatible, I would advise using forge instead. With version 4.0.0 we will move to neoforge, then the issue is resolved
