### ISSUE TITLE
Jade Shield crashing when blocking projectile

### ISSUE THREAD

**Issue by Feyreth** [Uraneptus/Sullys-Mod#98]
Experienced a crash on a server I'm running with Jade shields. Blocked an arrow from a Piglin, immediate crash. Here's the report.
Version: Minecraft 1.20.1, NeoForge 47.1.106
[crash-2024-09-13_22.01.20-client.txt](https://github.com/user-attachments/files/16993537/crash-2024-09-13_22.01.20-client.txt)

**Comment by Uraneptus** [comment]
Neoforge is not supported until 1.21. The changelog states that clearly

**Comment by Feyreth** [comment]
Ahh I see now. Would downgrading the mod version fix this issue by chance, at least until the next version? Or is this simply a problem that will persist with 1.20.1?

**Comment by Uraneptus** [comment]
Version 3.1.0 of sullysmod is compatible with Neoforge
But I'd advise just not using neoforge on 1.20.1
