### ISSUE TITLE
Splash potions thrown at a flinger totem splash on the totem

### ISSUE THREAD

**Issue by Beornslee** [Uraneptus/Sullys-Mod#99]
Splash and lingering potions thrown at jade flinger totems are flung as intended, but also splash on the totem itself, effectively duplicating the potion.

Steps to replicate:

1. Install the latest versions of Sully's Mod, Blueprint, and Geckolib on the latest version of forge 1.20.1
2. Throw a splash or lingering potion at a jade flinger totem

**Comment by Uraneptus** [comment]
Know bug, will be fixed in the next update!
